# Generated by Django 2.2.7 on 2020-12-21 11:16

from django.db import migrations
from graduate.models import Rank, Expectations, CharacterChange, AfterGraduating
from graduate.models import Position, Guardian, SatisfiedWithTheTraining


def add_default_data(apps, schema_editor):
    ranks = ['рядовой милиции', 'младший сержант милиции', 'сержант милиции', 'старший сержант милиции']
    for rank in ranks:
        new_rank = Rank(rank=rank)
        new_rank.save()
    positions = ['курсант', 'командир отделения', 'командир группы', 'старшина курса']
    for position in positions:
        new_position = Position(position=position)
        new_position.save()

    guardians = ['тетя', 'дядя', 'бабушка', 'дедушка', 'старшая сестра', 'старший брат']
    for guardian in guardians:
        new_guardian = Guardian(guardian=guardian)
        new_guardian.save()

    satisfactions = ['Не доволен (не довольна)', 'Доволен (довольна)', 'Затрудняюсь ответить']
    for satisfaction in satisfactions:
        new_satisfaction = SatisfiedWithTheTraining(satisfied=satisfaction)
        new_satisfaction.save()

    expectations = ['Не оправдались', 'Оправдались', 'Затрудняюсь ответить']
    for expectation in expectations:
        new_expectation = Expectations(expectation=expectation)
        new_expectation.save()

    character_changes = ['Стал (а) лучше', 'Стал (а) хуже', 'Затрудняюсь ответить']
    for change in character_changes:
        new_change = CharacterChange(change=change)
        new_change.save()

    after_graduatings = ['не продолжать службу', 'отслужить часть срока по контракту, затем смотреть по обстоятельствам',
                         'отслужить весь срок по контракту, затем смотреть по обстоятельствам',
                         'служить до полной выслуги лет', 'затрудняюсь ответить']
    for after in after_graduatings:
        new_after = AfterGraduating(after_graduating=after)
        new_after.save()

class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_data),
    ]
