# Generated by Django 2.2.7 on 2021-01-06 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0004_auto_20201222_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateform',
            name='divorced_live',
            field=models.IntegerField(blank=True, null=True, verbose_name='В разводе - живут'),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='has_children',
            field=models.IntegerField(default=0, verbose_name='Имеются ли дети?'),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='how_did_leaders_influence_explain',
            field=models.CharField(max_length=255, verbose_name='Как в целом повлияли на ваше профессиональное становление курсовые офицеры? (поясните ответ)'),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='how_did_teachers_influence_explain',
            field=models.CharField(max_length=255, verbose_name='Как в целом повлияли на ваше профессиональное становление преподаватели Академии МВД? (поясните ответ)'),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='interest',
            field=models.TextField(verbose_name='Ваши увлечения на данный момент'),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='is_satisfied_with_the_training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='graduate.SatisfiedWithTheTraining', verbose_name='Удовлетворены ли Вы тем как проходило Ваше обучение'),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='mother_father_data',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сведениями о родителях распологаю/не распологаю'),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='stepfather_stepmother_marriage_father',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проживает с отчимом/мачехой совместно/раздельно'),
        ),
        migrations.AlterField(
            model_name='graduateform',
            name='stepfather_stepmother_marriage_mother',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проживает с отчимом/мачехой совместно/раздельно'),
        ),
    ]
