# Generated by Django 2.2.7 on 2021-01-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0005_auto_20210106_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateform',
            name='what_keeps',
        ),
        migrations.AddField(
            model_name='graduateform',
            name='what_keeps',
            field=models.ManyToManyField(blank=True, to='graduate.WhatKeeps', verbose_name='Что Вас удерживает или мотивирует продолжать службу?'),
        ),
    ]
