# Generated by Django 2.2.7 on 2021-01-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0006_auto_20210106_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduateform',
            name='what_induce_to_quit',
        ),
        migrations.AddField(
            model_name='graduateform',
            name='what_induce_to_quit',
            field=models.ManyToManyField(to='graduate.WhatInduceToQuit', verbose_name='Что может побудить Вас уволиться?'),
        ),
    ]
