# Generated by Django 2.2.7 on 2021-01-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0007_auto_20210106_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_inform', models.CharField(max_length=255, verbose_name='Я информирован - по психологической помощи')),
            ],
            options={
                'verbose_name': 'Информирован',
                'verbose_name_plural': 'Информирован',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='graduateform',
            name='i_inform',
            field=models.ManyToManyField(blank=True, to='graduate.Inform', verbose_name='Я информирован'),
        ),
    ]
