# Generated by Django 2.2.7 on 2021-02-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduate', '0008_auto_20210106_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduateform',
            name='what_induce_to_quit',
            field=models.ManyToManyField(blank=True, to='graduate.WhatInduceToQuit', verbose_name='Что может побудить Вас уволиться?'),
        ),
    ]
