# Generated by Django 2.2.7 on 2021-02-18 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BekaScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('group', models.CharField(max_length=255, verbose_name='Группа')),
                ('date_of_fill', models.DateField(auto_now_add=True, verbose_name='Дата заполнения')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(blank=True, null=True, verbose_name='Номер вопроса')),
                ('question_text', models.CharField(max_length=255, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.IntegerField(verbose_name='Ответ')),
                ('beka_scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beka_scale.BekaScale', verbose_name='Анкета')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beka_scale.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='bekascale',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='beka_scale.Position', verbose_name='Должность'),
        ),
    ]
