# Generated by Django 2.2.7 on 2020-07-15 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(max_length=255, verbose_name='Дополнительно посещал')),
            ],
            options={
                'verbose_name': 'Вопрос 11 - Дополнительно посещал',
                'verbose_name_plural': 'Вопрос 11 - Дополнительно посещал',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(max_length=255, verbose_name='Решение было принято')),
            ],
            options={
                'verbose_name': 'Вопрос 15 - Решение было принято',
                'verbose_name_plural': 'Вопрос 15 - Решение было принято',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(max_length=255, verbose_name='Трудность при оформлении личного дела')),
            ],
            options={
                'verbose_name': 'Вопрос 17 - Трудность при оформлении личного дела',
                'verbose_name_plural': 'Вопрос 17 - Трудность при оформлении личного дела',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Educational',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational', models.CharField(max_length=255, verbose_name='Название учебного учреждения')),
            ],
            options={
                'verbose_name': 'Вопрос 05 - Окончил учебное учреждение',
                'verbose_name_plural': 'Вопрос 05 - Окончил учебное учреждение',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='EducationalPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_place', models.CharField(max_length=255, verbose_name='Расположение учебного учреждения (город)')),
            ],
            options={
                'verbose_name': 'Вопрос 07 - Расположение учебного учреждения',
                'verbose_name_plural': 'Вопрос 07 - Расположения учебных учреждений',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='GetEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('get_education', models.TextField(max_length=255, verbose_name='При обучении получение какого высшего образования для Вас важно')),
            ],
            options={
                'verbose_name': 'Вопрос 18 - При обучении получение какого высшего образования для Вас важноа',
                'verbose_name_plural': 'Вопрос 18 - При обучении получение какого высшего образования для Вас важно',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='GotInformationFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('got_from', models.CharField(max_length=255, verbose_name='Источник информации')),
            ],
            options={
                'verbose_name': 'Вопрос 14 - Информацию о поступлении получил',
                'verbose_name_plural': 'Вопрос 14 - Информацию о поступлении получил',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ImportantFor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.CharField(max_length=255, verbose_name='Важно для поступающего при выборе УО')),
            ],
            options={
                'verbose_name': 'Вопрос 12 - Важно для поступающего при выборе УО',
                'verbose_name_plural': 'Вопрос 12 - Важно для поступающего при выборе УО',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ImportantForSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('important', models.CharField(max_length=255, verbose_name='Важно для поступающего обучаться по специальности')),
            ],
            options={
                'verbose_name': 'Вопрос 13 - Важно для поступающего обучаться по специальности',
                'verbose_name_plural': 'Вопрос 13 - Важно для поступающего обучаться по специальности',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(max_length=255, verbose_name='В интересах')),
            ],
            options={
                'verbose_name': 'Вопрос 04 - Поступил в интересах',
                'verbose_name_plural': 'Вопрос 04 - Поступил в интересах',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='LetYou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('let_you', models.CharField(max_length=255, verbose_name='Поступление позволит')),
            ],
            options={
                'verbose_name': 'Вопрос 16 - Поступление позволит',
                'verbose_name_plural': 'Вопрос 16 - Поступление позволит',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='LivePlaceRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('educational_place_region', models.CharField(max_length=255, verbose_name='Область фактического проживания')),
            ],
            options={
                'verbose_name': 'Вопрос 08 - Область фактического проживания',
                'verbose_name_plural': 'Вопрос 08 - Области фактического проживания',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Questionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.IntegerField(default=1, verbose_name='Ваш пол')),
                ('year_of_birth', models.IntegerField(verbose_name='Год рождения')),
                ('year_count', models.IntegerField(verbose_name='Полных лет')),
                ('is_law_orientation', models.IntegerField(default=1, verbose_name='Обучались ли Вы в классе правовой направленности?')),
                ('average_mark', models.FloatField(verbose_name='Средний балл по аттестату, диплому')),
                ('mark_sum', models.IntegerField(blank=True, null=True, verbose_name='Сумма баллов по ЦТ (если сдавали)')),
                ('time_added', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время заполнения анкеты')),
                ('attend_extra', models.ManyToManyField(to='questioning.AttendExtra', verbose_name='Перед поступлением в Академию МВД Вы дополнительно посещали')),
                ('decision', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questioning.Decision', verbose_name='Решение о поступлении на обучение было принято')),
                ('difficulty', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questioning.Difficulty', verbose_name='Основная трудность при оформлении личного дела')),
                ('get_education', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questioning.GetEducation', verbose_name='Получение какого образования важно')),
                ('got_information_from', models.ManyToManyField(to='questioning.GotInformationFrom', verbose_name='Информацию о поступлении в Академия получил')),
                ('graduate', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questioning.Educational', verbose_name='Какое учебное заведение Вы заканчивали?')),
                ('important_for', models.ManyToManyField(to='questioning.ImportantFor', verbose_name='При выборе высшего УО важно')),
                ('important_for_spec', models.ManyToManyField(to='questioning.ImportantForSpec', verbose_name='Важно поступить и обучаться по специальности')),
                ('in_the_interests_of', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questioning.Interest', verbose_name='На учебу в Академию МВД Вы направляетесь в интересах')),
                ('let_you', models.ManyToManyField(to='questioning.LetYou', verbose_name='Поступление позволит')),
                ('live_region', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questioning.LivePlaceRegion', verbose_name='Область в которой Вы фактически проживаете')),
                ('place_of_last_education', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questioning.EducationalPlace', verbose_name='Последнее учебное заведение, которое Вы оканчивали, находится в')),
            ],
            options={
                'verbose_name': 'Анкета',
                'verbose_name_plural': 'Анкеты',
                'ordering': ('id',),
            },
        ),
    ]
