# Generated by Django 2.2.7 on 2020-07-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questioning', '0002_auto_20200716_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='let_you',
            field=models.ManyToManyField(to='questioning.LetYou', verbose_name='Поступление Вам позволит'),
        ),
    ]
