# Generated by Django 2.2.7 on 2020-07-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_ability_activity_anketa_guardian_interest_messenger_motherfather_participationineducation_particular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='relatives_record',
            field=models.ManyToManyField(blank=True, to='course.RelativesRecord', verbose_name='Родственники на учете у врачей'),
        ),
    ]
