# Generated by Django 2.2.7 on 2020-07-31 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200730_1141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='motherfather',
            options={'ordering': ('id',), 'verbose_name': 'Родитель (родные)', 'verbose_name_plural': 'Родители (родные)'},
        ),
        migrations.AlterModelOptions(
            name='particularqualities',
            options={'ordering': ('id',), 'verbose_name': 'Особенность', 'verbose_name_plural': 'Особенности'},
        ),
        migrations.AlterField(
            model_name='anketa',
            name='guardian',
            field=models.ManyToManyField(blank=True, to='course.Guardian', verbose_name='Опекуны'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='messenger',
            field=models.ManyToManyField(to='course.Messenger', verbose_name='Какие мессенджеры / мобильные приложения предпочитаете для общения?'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='mother_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.MotherFather', verbose_name='Мать Отец'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='particular_qualities',
            field=models.ManyToManyField(to='course.ParticularQualities', verbose_name='Отметьте свои особенности, которых вы стесняетесь, которые вас беспокоят'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='relationship',
            field=models.ManyToManyField(to='course.Relationship', verbose_name='Какие взаимоотношения преобладают между вашими родителями, лицами их заменяющими)'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='relatives_record',
            field=models.ManyToManyField(blank=True, to='course.RelativesRecord', verbose_name='Кто-либо из ваших близких родственников (родные отец, мать, бабушки, дедушки, тети, дяди)'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='stepmother_stepfather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.StepmotherStepfather', verbose_name='Мачеха Отчим'),
        ),
    ]
