# Generated by Django 2.2.7 on 2020-08-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200731_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('group_number',), 'verbose_name': 'Группа курсантов', 'verbose_name_plural': 'Группы курсантов'},
        ),
        migrations.AlterField(
            model_name='anketa',
            name='year_of_graduation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год окончания'),
        ),
    ]
