# Generated by Django 2.2.7 on 2021-08-02 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20210802_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anketa',
            name='kind',
        ),
    ]
