# Generated by Django 2.2.7 on 2021-01-06 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер вопроса'),
        ),
        migrations.AlterField(
            model_name='questionary',
            name='date_of_birth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Дата рождения'),
        ),
    ]
