# Generated by Django 2.2.7 on 2021-03-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big_test', '0002_auto_20210106_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionary',
            name='timer',
            field=models.IntegerField(blank=True, null=True, verbose_name='Таймер'),
        ),
    ]
