# Generated by Django 2.2.7 on 2021-07-29 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('big_test', '0003_questionary_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionary',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Group', verbose_name='Группа'),
        ),
    ]
